# Packages the generated slides into a copy of NiCE's corporate PowerPoint template.
#
#   node tools\deck\build-deck.mjs
#   powershell -File tools\deck\package-deck.ps1
#
# WHY SURGERY ON A TEMPLATE RATHER THAN A DECK FROM SCRATCH
# The look and feel was asked for explicitly. Building a new pptx would mean approximating the
# NiCE brand; copying the template keeps the real thing: the slide master, its 32 layouts, the
# logo artwork and the theme colours. Every generated slide is bound to the template's "blank"
# layout, which already carries the NiCE furniture, so the deck opens on-brand and every shape
# stays editable in PowerPoint.
#
# WHY THIS TEMPLATE
# 2026 SKO Annual Planning Template, whose theme colours match the live CSS custom properties
# on nice.com almost exactly: dk2 #22212B, lt2 #F2EFEB, accent1 #3694FC, accent6 #00E2A0.
# That agreement is the evidence it is the current brand rather than an old one.
#
# NO NEW DEPENDENCIES. There is no Python on this machine and pptxgenjs would be an install, so
# the XML is generated by hand and zipped with System.IO.Compression.

param(
  [string]$Template = 'C:\Users\oattia\OneDrive - NiCE Ltd\EVENTS\251007_SKO2026\2026 SKO Annual Planning Template - QCR - CX INTL.pptx',
  [string]$OutFile = ''
)

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.IO.Compression.FileSystem
Add-Type -AssemblyName System.IO.Compression

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent (Split-Path -Parent $here)
$outDir = Join-Path $here 'out'
if ($OutFile -eq '') { $OutFile = Join-Path $repoRoot 'docs\NiCE-Digital-Room.pptx' }

if (-not (Test-Path $Template)) { Write-Error "Template not found: $Template"; exit 1 }
$count = [int](Get-Content (Join-Path $outDir 'count.txt') -Raw).Trim()
Write-Host "Slides to insert: $count"

New-Item -ItemType Directory -Force -Path (Split-Path -Parent $OutFile) | Out-Null
Copy-Item $Template $OutFile -Force

# The layout every generated slide binds to. 8 is "blank": no title or body placeholder to
# fight with, but all 25 pieces of NiCE furniture still inherited from the layout and master.
$LAYOUT = 'slideLayout8.xml'

$zip = [System.IO.Compression.ZipFile]::Open($OutFile, [System.IO.Compression.ZipArchiveMode]::Update)

function Read-Entry([string]$name) {
  $e = $zip.Entries | Where-Object { $_.FullName -eq $name } | Select-Object -First 1
  if (-not $e) { return $null }
  $sr = New-Object System.IO.StreamReader($e.Open())
  $text = $sr.ReadToEnd()
  $sr.Close()
  $text
}

function Write-Entry([string]$name, [string]$content) {
  $existing = $zip.Entries | Where-Object { $_.FullName -eq $name } | Select-Object -First 1
  if ($existing) { $existing.Delete() }
  $entry = $zip.CreateEntry($name)
  $sw = New-Object System.IO.StreamWriter($entry.Open(), (New-Object System.Text.UTF8Encoding($false)))
  $sw.Write($content)
  $sw.Close()
}

# --- 1. Remove the template's own slides -------------------------------------------------
# The template ships 19 planning slides. They are not ours and must not appear, but the
# layouts, master and theme they depend on all stay.
$oldSlides = @($zip.Entries | Where-Object { $_.FullName -match '^ppt/slides/(_rels/)?slide\d+\.xml(\.rels)?$' })
Write-Host "Removing $($oldSlides.Count) template slide parts"
foreach ($e in $oldSlides) { $e.Delete() }

# Notes slides reference slides by rId and would dangle once the slides are gone.
$oldNotes = @($zip.Entries | Where-Object { $_.FullName -match '^ppt/notesSlides/' })
foreach ($e in $oldNotes) { $e.Delete() }

# --- 2. Add the generated slides ---------------------------------------------------------
for ($i = 1; $i -le $count; $i++) {
  # ReadAllText with an explicit UTF8 encoding, NOT Get-Content -Raw. Windows PowerShell 5.1
  # reads as ANSI by default, so a middot came back as two characters and was then written out
  # as UTF-8 again: PowerPoint showed "Â·" and "2â€¯147". Double-encoding, not a font problem.
  $xml = [System.IO.File]::ReadAllText((Join-Path $outDir "slide$i.xml"), [System.Text.Encoding]::UTF8)
  Write-Entry "ppt/slides/slide$i.xml" $xml
  $rels = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' +
    '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">' +
    '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" ' +
    "Target=`"../slideLayouts/$LAYOUT`"/></Relationships>"
  Write-Entry "ppt/slides/_rels/slide$i.xml.rels" $rels
}

# --- 2b. Remove the template's SKO footer lockup from OUR copy of the layout -------------
# The bottom-right mark reads "NiCE | Global Sales Kickoff", which is wrong on this deck. It is
# vector artwork, not text, so it cannot simply be reworded; the group is removed here and
# build-deck.mjs draws "NiCE | Digital Room" on each slide instead.
#
# Identified by position rather than by name: it sits at x=9485410, y=6458508, hard against the
# bottom-right corner of a 12192000 x 6858000 slide. Matching on the name "Group 1" would be
# luck.
$layoutXml = Read-Entry "ppt/slideLayouts/$LAYOUT"
$ldoc = New-Object System.Xml.XmlDocument
$ldoc.LoadXml($layoutXml)
$lns = New-Object System.Xml.XmlNamespaceManager($ldoc.NameTable)
$lns.AddNamespace('p', 'http://schemas.openxmlformats.org/presentationml/2006/main')
$lns.AddNamespace('a', 'http://schemas.openxmlformats.org/drawingml/2006/main')
$spTree = $ldoc.SelectSingleNode('//p:cSld/p:spTree', $lns)
$removed = 0
foreach ($child in @($spTree.ChildNodes)) {
  if ($child.LocalName -ne 'grpSp') { continue }
  $off = $child.SelectSingleNode('.//a:off', $lns)
  if (-not $off) { continue }
  if ([int64]$off.GetAttribute('x') -gt 9000000 -and [int64]$off.GetAttribute('y') -gt 6000000) {
    [void]$spTree.RemoveChild($child)
    $removed++
  }
}
if ($removed -gt 0) {
  Write-Entry "ppt/slideLayouts/$LAYOUT" $ldoc.OuterXml
  Write-Host "Removed $removed footer lockup group(s) from $LAYOUT"
} else {
  Write-Host "WARNING: no footer lockup found in $LAYOUT. The SKO mark may still appear."
}

# --- 3. Rebuild presentation relationships ----------------------------------------------
# Slide relationships are replaced wholesale; everything else (master, notesMaster, theme,
# presProps, viewProps, tableStyles) is preserved exactly as the template had it.
$prels = Read-Entry 'ppt/_rels/presentation.xml.rels'
$doc = New-Object System.Xml.XmlDocument
$doc.PreserveWhitespace = $false
$doc.LoadXml($prels)
$ns = $doc.DocumentElement.NamespaceURI

$toRemove = @()
foreach ($n in $doc.DocumentElement.ChildNodes) {
  if ($n.GetAttribute('Type') -like '*/slide') { $toRemove += $n }
  if ($n.GetAttribute('Type') -like '*/notesSlide') { $toRemove += $n }
}
foreach ($n in $toRemove) { [void]$doc.DocumentElement.RemoveChild($n) }

# Fresh ids that cannot collide with the ones the template still uses.
$maxId = 0
foreach ($n in $doc.DocumentElement.ChildNodes) {
  $m = [regex]::Match($n.GetAttribute('Id'), '\d+')
  if ($m.Success -and [int]$m.Value -gt $maxId) { $maxId = [int]$m.Value }
}

$slideRIds = @()
for ($i = 1; $i -le $count; $i++) {
  $rid = 'rId' + ($maxId + $i)
  $slideRIds += $rid
  $rel = $doc.CreateElement('Relationship', $ns)
  $rel.SetAttribute('Id', $rid)
  $rel.SetAttribute('Type', 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide')
  $rel.SetAttribute('Target', "slides/slide$i.xml")
  [void]$doc.DocumentElement.AppendChild($rel)
}
Write-Entry 'ppt/_rels/presentation.xml.rels' $doc.OuterXml

# --- 4. Rewrite the slide id list --------------------------------------------------------
$pres = Read-Entry 'ppt/presentation.xml'
$sldIds = ''
for ($i = 0; $i -lt $count; $i++) {
  # Slide ids must be unique and >= 256. Starting at 300 keeps clear of the template's own.
  $sldIds += '<p:sldId id="' + (300 + $i) + '" r:id="' + $slideRIds[$i] + '"/>'
}
$pres = [regex]::Replace($pres, '<p:sldIdLst>.*?</p:sldIdLst>', "<p:sldIdLst>$sldIds</p:sldIdLst>", 'Singleline')
Write-Entry 'ppt/presentation.xml' $pres

# --- 5. Content types --------------------------------------------------------------------
$ct = Read-Entry '[Content_Types].xml'
$ct = [regex]::Replace($ct, '<Override PartName="/ppt/slides/slide\d+\.xml"[^>]*/>', '')
$ct = [regex]::Replace($ct, '<Override PartName="/ppt/notesSlides/[^"]*"[^>]*/>', '')
$adds = ''
for ($i = 1; $i -le $count; $i++) {
  $adds += '<Override PartName="/ppt/slides/slide' + $i + '.xml" ' +
    'ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>'
}
$ct = $ct -replace '</Types>', ($adds + '</Types>')
Write-Entry '[Content_Types].xml' $ct

$zip.Dispose()

$size = [math]::Round((Get-Item $OutFile).Length / 1MB, 1)
Write-Host ""
Write-Host "Wrote $OutFile  ($size MB, $count slides)"
Write-Host "Template: $(Split-Path -Leaf $Template)"
